# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bae6bd13381e572e08ebbaec9deb1a9388f37700c8ed430863baf217025573485181f84791efe09d6c08ed6cf947644b626cfe78e29a7a23203602fee109084e

test:
  secret_key_base: c2f02dc37859494e43f926155e7bdd0b1a1c3539a2d5a2d73cc4d90d3bf17e982f17c39d32444e19bcdee7f1b502469cd2eabff5c4749b21d16584c5f4542af7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
